initializr:
  env:
    boms:
      spring-cloud:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-dependencies
        versionProperty: spring-cloud.version
        version: Hoxton.SR4
      mybatis:
        groupId: org.mybatis.spring.boot
        artifactId: mybatis-spring-boot-starter
        versionProperty: mybatis.version
        version: 2.1.4
      h2:
        groupId: com.h2database
        artifactId: h2
        versionProperty: h2.version
        version: 1.4.200
      mysql:
        groupId: mysql
        artifactId: mysql-connector-java
        versionProperty: mysql.version
        version: 8.0.22
      #      redis:
      #        groupId: com.h2database
      #        artifactId: h2
      #        versionProperty: redis.version
      #        version: 2.1.4

    platform:
      compatibility-range: "2.1.0.RELEASE"
      v1-format-compatibility-range: "[2.0.0.RELEASE,2.4.0-M1)"
      v2-format-compatibility-range: "2.4.0-M1"
    repositories:
      spring-releases:
        name: Spring Releases
        url: https://repo.spring.io/release
      sonatype-snapshots:
        name: Sonatype Snapshots
        url: https://oss.sonatype.org/content/repositories/snapshots/
        releasesEnabled: false
        snapshotsEnabled: true
  dependencies:
    - name: Tools
      content:
        - name: google gson
          id: gson
          groupId: com.google.code.gson
          artifactId: gson
          description: json tools
          starter: false
    - name: SQL
      content:
        - name: MyBatis-plus Framework
          id: mybatisplus
          starter: false
          groupId: com.baomidou
          artifactId: mybatis-plus-boot-starter
          version: 3.4.2
        - name: H2 Database
          id: h2
          description: Provides a fast in-memory database that supports JDBC API and R2DBC access, with a small (2mb) footprint. Supports embedded and server modes as well as a browser based console application.
          facets:
            - native
          groupId: com.h2database
          artifactId: h2
          scope: test
          starter: false
          version: 1.4.200
        - name: MySQL Driver
          id: mysql
          description: MySQL JDBC and R2DBC driver.
          facets:
            - native
          groupId: mysql
          artifactId: mysql-connector-java
          starter: false
          version: 8.0.22
    - name: NoSQL
      content:
        - name: Spring Data Redis (Access+Driver)
          id: redis
          description: Advanced and thread-safe Java Redis client for synchronous, asynchronous, and reactive usage. Supports Cluster, Sentinel, Pipelining, Auto-Reconnect, Codecs and much more.
          groupId: org.springframework.boot
          artifactId: spring-boot-starter-data-redis
          starter: true
  types:
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive.
      tags:
        build: gradle
        format: project
      defaultValue: false
      action: /starter.zip
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive.
      tags:
        build: maven
        format: project
      defaultValue: true
      action: /starter.zip
  packagings:
    - name: Jar
      id: jar
      default: true
  group-id:
    value: com.xingsk
  description:
    value: xingshukui project
  javaVersions:
    - id: 1.8
      default: true
  languages:
    - name: Java
      id: java
      default: true
  bootVersions:
    - name : 2.3.1
      id: 2.3.1.RELEASE
      default: true